openApi: 3.0.3

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student-course-file-tracker?useSSL=false&serverTimezone=UTC
    username: hbstudent
    password: hbstudent
  profiles:
    active: #{spring.profiles.active}
  application:
    name: #{project.name}
    version: #{project.version}
    desc: #{project.description}
  jms:
    pub-sub-domain: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

# custom app properties
info:
  app:
    name: ${spring.application.name}
    desc: ${spring.application.desc}
    version: ${spring.application.version}
    author: BabinKuk
    build-timestamp: #{maven.build.timestamp}
    profiles:
      active: ${spring.profiles.active}

# expose actuator metrics endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - 'health'
#          - 'info'
        info:
          env:
            enabled: true
